### ISSUE TITLE
more info on scheduler

### ISSUE THREAD

**Issue by kose-y** [chris-german/Hoffman2Tutorials#2]
Hi Chris, 

I think it would be more instructive to give the name of the job scheduler (Univa Grid Engine, according to https://www.hoffman2.idre.ucla.edu/computing/policy/) running on the server, and give pointers to learn more about commands available on the job scheduler.

**Comment by Hua-Zhou** [comment]
Thanks for the suggestion, @kose-y. Just added a section explicitly mentioning UGE and giving links to commonly used UGE commands.
